[build]
  # Build command - using npm with legacy peer deps to handle dependency conflicts
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node version - using Node 20 LTS (supported by Netlify)
  NODE_VERSION = "20"
  
  # Disable npm audit to speed up builds
  NPM_CONFIG_AUDIT = "false"
  
  # Use legacy peer deps to handle dependency conflicts
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache video files when added later
[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/thumbnails/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Optimize images and assets
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

# Handle large files (for when videos are added)
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

